# Generated by Django 6.0.2 on 2026-02-23 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='classes.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('essay', 'Essay'), ('truefalse', 'True/False')], max_length=20)),
                ('points', models.IntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
